export const indiaSubdivisionOptions: Array<{ name: string; value: string }> = [
  { name: 'Andhra Pradesh (IN-AP)', value: 'IN-AP' },
  { name: 'Arunachal Pradesh (IN-AR)', value: 'IN-AR' },
  { name: 'Assam (IN-AS)', value: 'IN-AS' },
  { name: 'Bihar (IN-BR)', value: 'IN-BR' },
  { name: 'Chhattisgarh (IN-CT)', value: 'IN-CT' },
  { name: 'Goa (IN-GA)', value: 'IN-GA' },
  { name: 'Gujarat (IN-GJ)', value: 'IN-GJ' },
  { name: 'Haryana (IN-HR)', value: 'IN-HR' },
  { name: 'Himachal Pradesh (IN-HP)', value: 'IN-HP' },
  { name: 'Jharkhand (IN-JH)', value: 'IN-JH' },
  { name: 'Karnataka (IN-KA)', value: 'IN-KA' },
  { name: 'Kerala (IN-KL)', value: 'IN-KL' },
  { name: 'Madhya Pradesh (IN-MP)', value: 'IN-MP' },
  { name: 'Maharashtra (IN-MH)', value: 'IN-MH' },
  { name: 'Manipur (IN-MN)', value: 'IN-MN' },
  { name: 'Meghalaya (IN-ML)', value: 'IN-ML' },
  { name: 'Mizoram (IN-MZ)', value: 'IN-MZ' },
  { name: 'Nagaland (IN-NL)', value: 'IN-NL' },
  { name: 'Odisha (IN-OR)', value: 'IN-OR' },
  { name: 'Punjab (IN-PB)', value: 'IN-PB' },
  { name: 'Rajasthan (IN-RJ)', value: 'IN-RJ' },
  { name: 'Sikkim (IN-SK)', value: 'IN-SK' },
  { name: 'Tamil Nadu (IN-TN)', value: 'IN-TN' },
  { name: 'Telangana (IN-TG)', value: 'IN-TG' },
  { name: 'Tripura (IN-TR)', value: 'IN-TR' },
  { name: 'Uttarakhand (IN-UT)', value: 'IN-UT' },
  { name: 'Uttar Pradesh (IN-UP)', value: 'IN-UP' },
  { name: 'West Bengal (IN-WB)', value: 'IN-WB' },
  { name: 'Andaman and Nicobar Islands (Territory) (IN-AN)', value: 'IN-AN' },
  { name: 'Chandigarh (Territory) (IN-CH)', value: 'IN-CH' },
  { name: 'Dadra and Nagar Haveli and Daman and Diu (Territory) (IN-DH)', value: 'IN-DH' },
  { name: 'Delhi (Territory) (IN-DL)', value: 'IN-DL' },
  { name: 'Jammu and Kashmir (Territory) (IN-JK)', value: 'IN-JK' },
  { name: 'Ladakh (Territory) (IN-LA)', value: 'IN-LA' },
  { name: 'Lakshadweep (Territory) (IN-LD)', value: 'IN-LD' },
  { name: 'Puducherry (Territory) (IN-PY)', value: 'IN-PY' },
];

